# Taken from: https://github.com/dmnemec/copy_file_to_another_repo_action
name: Push File

on: push

jobs:
# Taken from: https://github.com/dmnemec/copy_file_to_another_repo_action
name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Pushes test file
    #   uses: dmnemec/copy_file_to_another_repo_action@main
    #   env:
    #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    #   with:
    #     source_file: 'cv.pdf'
    #     destination_repo: 'CharlesEtienneLavoie/YOUR_WEBSITE_REPO' # TODO: Update this when you have a website repo
    #     destination_folder: 'static'
    #     user_email: 'celavoie96@gmail.com'
    #     user_name: 'CharlesEtienneLavoie'
    #     destination_branch: 'master'
    #     commit_message: 'update cv'